apiVersion: v1
kind: Service
metadata:
  name: mess-keycloak-service
  labels:
    app: keycloak
    family: mess
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: NodePort