apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud
    family: mess
  name: mess-nextcloud-service
spec:
  ports:
  - port: 8012
    protocol: TCP
    targetPort: 80
  selector:
    app: nextcloud
  externalIPs:
    - 10.112.17.113
