apiVersion: apps/v1
kind: Deployment
metadata:
  name: mess-nextcloud
  labels:
    app: nextcloud
    family: mess
    kube-monkey/enabled: enabled
    kube-monkey/identifier: nextcloud
    kube-monkey/mtbf: "1"
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
        kube-monkey/enabled: enabled
        kube-monkey/identifier: nextcloud
        kube-moneky/mtbf: "1"
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: "1"
    spec:
      containers:
        - name: mess-nextcloud
          image: nextcloud:25
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: NEXTCLOUD_ADMIN_USER
              value: "admin"
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: "Possu123!"
            - name: LOGLEVEL
              value: "0"
            #- name: DB_TYPE
            #  value: "postgresql"
            #- name: POSTGRES_DB
            #  value: "nextcloud"
            #- name: POSTGRES_USER
            #  valueFrom:
            #    configMapKeyRef:
            #      name: postgres-config
            #      key: POSTGRES_USER
            #- name: POSTGRES_PASSWORD
            #  valueFrom:
            #    secretKeyRef:
            #      name: postgres-secret
            #      key: POSTGRES_PASSWORD
            #- name: POSTGRES_HOST
            #  value: "mess-postgres-service:5432"  
          ports:
            - containerPort: 80
              name: root-http
          readinessProbe:
            httpGet:
              path: /
              port: 80
