apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud
    family: mess
  name: mess-nextcloud-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nextcloud
  type: ClusterIP
