apiVersion: apps/v1
kind: Deployment
metadata:
  name: mess-nextcloud
  labels:
    app: nextcloud
    family: mess
    kube-monkey/enabled: enabled
    kube-monkey/identifier: nextcloud
    kube-monkey/mtbf: "1"
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
        kube-monkey/enabled: enabled
        kube-monkey/identifier: nextcloud
        kube-moneky/mtbf: "1"
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: "1"
    spec:
      hostname: nexthost
      containers:
        - name: mess-nextcloud
          image: nextcloud:25
          resources:
            requests:
              memory: "2048Mi"
              cpu: "500m"
            limits:
              memory: "4096Mi"
              cpu: "750m"
          env:
            - name: NEXTCLOUD_ADMIN_USER
              value: "admin"
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: "Possu123!"
            - name: LOGLEVEL
              value: "0"
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              value: oc_admin
            - name: MYSQL_PASSWORD
              value: Possu123!
            - name: MYSQL_HOST
              value: "mariadb-service:3306"
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "localhost 192.168.49.2"
          ports:
            - containerPort: 80
              name: root-http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: 80
