apiVersion: apps/v1
kind: Deployment
metadata:
  name: mess-nextcloud
  labels:
    app: nextcloud
    family: mess
    kube-monkey/enabled: enabled
    kube-monkey/identifier: nextcloud
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
        kube-monkey/enabled: enabled
        kube-monkey/identifier: nextcloud
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: '1'
    spec:
      containers:
      - name: mess-nextcloud
        image: nextcloud:latest
        ports:
        - containerPort: 80
          name: root-http
        readinessProbe:
          httpGet:
            path: /
            port: 80
