apiVersion: apps/v1
kind: Deployment
metadata:
  name: mess-redis
  labels:
    app: redis
    family: mess
    kube-monkey/enabled: enable
    kube-monkey/identifier: redis
    kube-monkey/mtbf: "1"
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        kube-monkey/enabled: enable
        kube-monkey/identifier: redis
        kube-monkey/mtbf: "1"
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: '1'
    spec:
      containers:
      - name: mess-redis
        image: redis:7
        ports:
        - containerPort: 6379
          name: root-http
        
