apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    family: mess
  name: mess-redis-service
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
