apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    family: mess
  name: mess-redis-service
spec:
  # allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: redis
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
