---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-monkey-config-map
  namespace: kube-system
data:
  config.toml: |
    [kubemonkey]
    dry_run = false
    run_hour = 12
    start_hour = 13
    end_hour = 14
    blacklisted_namespaces = ["kube-system"]
    whitelisted_namespaces = [ "default" ]
    time_zone = "Europe/Helsinki"
    graceperiod_sec= 10
    [debug]
    enabled= true
    schedule_immediate_kill= true
    [notifications]
      enabled = false
      reportSchedule = true
      [notifications.attacks]
        endpoint = "http://xxxx"
        message = '{"what": "kubemonkey id {$kubemonkey}", "victim": "{$name}", "when": "{$timestamp}"}'
        headers = ["Content-Type:application/json"]
