apiVersion: apps/v1
kind: Deployment
metadata:
  name: mess-postgres
  labels:
    app: postgres
    family: mess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: mess-postgres
        image: postgres:latest
        ports:
        - containerPort: 80
          name: root-http
        env:
          - name: POSTGRES_PASSWORD
            value: password