apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mess-postgres
  labels:
    family: mess
    app: postgres
spec:
  serviceName: mess-postgres-service
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          # This forces the postgres user into use,
          # when running commands from yaml instead of docker image
          securityContext:
            runAsUser: 999
          envFrom:
          - configMapRef:
              name: postgres-config
          - secretRef:
              name: postgres-secret
          ports:
            - name: web
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          command: ["postgres"]
          # Command in progress to create password for users
          #command: ["postgres", "psql", "-c", "\"ALTER USER postgres PASSWORD '$(POSTGRES_PASSWORD)';\""]
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi