apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mess-postgres
  labels:
    family: mess
    app: postgres
spec:
  serviceName: mess-postgres-service
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          securityContext:
            runAsUser: 999
          envFrom:
          - configMapRef:
              name: postgres-config
          - secretRef:
              name: postgres-secret
          env:
          - name: PGDATA
            value: /var/lib/postgresql/data/mess/
          ports:
            - name: web
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
