apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /nextcloud
        pathType: Prefix
        backend:
          service:
            name: mess-nextcloud-service
            port:
              number: 80
      - path: /redis
        pathType: Prefix
        backend:
          service:
            name: mess-redis-service
            port:
              number: 6379
      - path: /postgres
        pathType: Prefix
        backend:
          service:
            name: mess-postgres-service
            port:
              number: 8080
      - path: /keycloak
        pathType: Prefix
        backend:
          service:
            name: mess-keycloak-service
            port:
              number: 8080