apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-configmap
data:
  primary.cnf: |
    [mariadb]
    log-bin                         # enable binary logging
    log-basename=my-mariadb         # used to be independent of hostname changes (otherwise is in datadir/mysql)

  replica.cnf: |
    [mariadb]
    log-basename=my-mariadb         # used to be independent of hostname changes (otherwise is in datadir/mysql)

  primary.sql: |
    CREATE USER 'repluser'@'%' IDENTIFIED BY 'replsecret';
    GRANT REPLICATION REPLICA ON *.* TO 'repluser'@'%';
    CREATE DATABASE IF NOT EXISTS nextcloud;
    CREATE USER 'oc_admin'@'%' IDENTIFIED BY 'Possu123!';
    GRANT ALL PRIVILEGES ON `%`.* TO 'oc_admin%'@'%' IDENTIFIED BY 'Possu123!' WITH GRANT OPTION;
    FLUSH PRIVILEGES;

  secondary.sql: |
    CHANGE MASTER TO 
    MASTER_HOST='mariadb-0.mariadb-service.default.svc.cluster.local',
    MASTER_USER='repluser',
    MASTER_PASSWORD='replsecret',
    MASTER_CONNECT_RETRY=10;
