apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      initContainers:
        - name: init-mariadb
          image: bitnami/mariadb:10.9.5
          imagePullPolicy: Always
          command:
            - bash
            - "-c"
            - |
              set -ex
              echo 'Starting init-mariadb';
              # Check config map to directory that already exists 
              # (but must be used as a volume for main container)
              ls /mnt/config-map
              # Statefulset has sticky identity, number should be last
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              # Copy appropriate conf.d files from config-map to 
              # mariadb-config volume (emptyDir) depending on pod number
              if [[ $ordinal -eq 0 ]]; then
                # This file holds SQL for connecting to primary
                cp /mnt/config-map/primary.cnf /etc/mysql/conf.d/server-id.cnf
                # Create the users needed for replication on primary on a volume
                # initdb (emptyDir)
                cp /mnt/config-map/primary.sql /docker-entrypoint-initdb.d
              else
                # This file holds SQL for connecting to secondary
                cp /mnt/config-map/replica.cnf /etc/mysql/conf.d/server-id.cnf
                # On replicas use secondary configuration on initdb volume
                cp /mnt/config-map/secondary.sql /docker-entrypoint-initdb.d
              fi
              # Add an offset to avoid reserved server-id=0 value.
              echo server-id=$((3000 + $ordinal)) >> etc/mysql/conf.d/server-id.cnf
              ls /etc/mysql/conf.d/
              cat /etc/mysql/conf.d/server-id.cnf
          volumeMounts:
            - name: mariadb-config-map
              mountPath: /mnt/config-map
            - name: mariadb-config
              mountPath: /etc/mysql/conf.d/
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      containers:
        - name: mariadb
          image: bitnami/mariadb:10.9.5
          ports:
            - containerPort: 3306
              name: mariadb
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-root-password
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: username
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
            - name: MARIADB_DATABASE
              value: "nextcloud"
            # - name: MARIADB_REPLICATION_MODE
            #   value: master
            # - name: MARIADB_REPLICATION_USER
            #   value: replicator
            # - name: MARIADB_REPLICATION_PASSWORD
            #   value: pleaseReplicate
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/mysql/
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mariadb-config-map
          configMap:
            name: mariadb-configmap
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir
        - name: mariadb-config
          emptyDir: {}
        - name: initdb
          emptyDir: {}
